import { TemplateRef } from '@angular/core';
import { ColumnPinningPosition, GridColumnDataType, IColumnEditorOptions, IColumnPipeArgs, IgxFilteringOperand, IgxSummaryOperand, ISortingStrategy } from 'igniteui-angular/core';
import { IgxColumnTemplateContext, IgxCellTemplateContext, IgxSummaryTemplateContext } from '../common/grid.interface';

export interface IgxColumnConfig {
    field?: string;
    merge?: boolean;
    header?: string;
    title?: string;
    sortable?: boolean;
    selectable?: boolean;
    groupable?: boolean;
    editable?: boolean;
    filterable?: boolean;
    resizable?: boolean;
    autosizeHeader?: boolean;
    hasSummary?: boolean;
    hidden?: boolean;
    disableHiding?: boolean;
    disablePinning?: boolean;
    width?: string;
    maxWidth?: string;
    headerClasses?: string;
    headerStyles?: any;
    headerGroupClasses?: string;
    headerGroupStyles?: any;
    cellClasses?: any;
    cellStyles?: any;
    formatter?: (value: any, rowData?: any) => any;
    summaryFormatter?: (summary: any, summaryOperand: IgxSummaryOperand) => any;
    filteringIgnoreCase?: boolean;
    sortingIgnoreCase?: boolean;
    searchable?: boolean;
    dataType?: GridColumnDataType;
    collapsibleIndicatorTemplate?: TemplateRef<IgxColumnTemplateContext>;
    rowEnd?: number;
    colEnd?: number;
    rowStart?: number;
    colStart?: number;
    additionalTemplateContext?: any;
    minWidth?: string;
    pinningPosition?: ColumnPinningPosition;
    pinned?: boolean;
    summaries?: any;
    disabledSummaries?: string[];
    filters?: IgxFilteringOperand;
    sortStrategy?: ISortingStrategy;
    mergingComparer?: (prevRecord: any, record: any, field: string) => boolean;
    groupingComparer?: (a: any, b: any, currRec?: any, groupRec?: any) => number;
    summaryTemplate?: TemplateRef<IgxSummaryTemplateContext>;
    bodyTemplate?: TemplateRef<IgxCellTemplateContext>;
    headerTemplate?: TemplateRef<IgxColumnTemplateContext>;
    inlineEditorTemplate?: TemplateRef<IgxCellTemplateContext>;
    errorTemplate?: TemplateRef<IgxCellTemplateContext>;
    filterCellTemplate?: TemplateRef<IgxColumnTemplateContext>;
    pipeArgs?: IColumnPipeArgs;
    editorOptions?: IColumnEditorOptions;
    visibleWhenCollapsed?: boolean;
}
